//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETicaretProject.DB
{
    using System;
    
    public enum MemberType : int
    {
        Admin = 10,
        Editor = 8,
        Customer = 0
    }
}
